services:
  #NextJS
  app:
    build:
      context: .
    image: nextjs-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules 
        - action: rebuild
          path: package.json
          
  #Postgres DB
  db:
    image: postgres:15-alpine
    environment:
    - POSTGRES_USER=postgres    
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=next-prisma-db
    ports:
      - "5432:5432"
          