version: '3.8'

services:
  #BACKEND
  express:
    container_name: express
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    command: npm run dev
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    env_file:
      - .env

  #DATABASE
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db