version: '3.8'

services: 
  #BACKEND
  express-api:
    container_name: express-api
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    command: npm run dev
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    env_file:
      - .env
  
  #DATABASE
  postgres:
    container_name: postgres
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres